### ISSUE TITLE
Flaws images 70 && 2815

### ISSUE THREAD

**Issue by nicolastah** [nperraud/download-celebA-HQ#4]
Hello and thanks for sharing your code!  :smile:

I've been browsing in the generated images and most of them are of high quality. 
However, I found that images **70** and **2815** are not that great.

Image **70** -  half of the face is cut
![imghq00070](https://user-images.githubusercontent.com/31907549/43496038-a08d01a2-956d-11e8-92a3-511ddbea43a6.jpg)

Image **2815** - there is an eye in the mouth
![imghq02815](https://user-images.githubusercontent.com/31907549/43496015-852a87ea-956d-11e8-8d96-2b0a22c934f2.jpg)

Is it the same for you? Is it the same from the original repo?(NIVIDIA)
Did you find other images with small flaws?

**Comment by nperraud** [comment]
Thanks for reporting this. I have not noticed anything special yet. Problematically, I do not have the dataset on my computer anymore so I need to re-run the scripts. I will let you know as soon as they are done.

**Comment by nperraud** [comment]
I run the script on two different computers and go the same results. The code is some kind of package of the Nvidia code. So I believe those problematic images were also in the original dataset.

I just started to create a list of the bad images so that we can discard them. 
https://github.com/nperraud/download-celebA-HQ/blob/master/bad_images.txt
Please let me know if you find other problematic images.

**Comment by nicolastah** [comment]
Thanks again!  :thumbsup:
 I'll let you know if I find other bad images.
